### ISSUE TITLE
[Feature Suggestion] Curios Compat for certain modifiers

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Upgrade-Modifiers#1]
I think it would be cool to have Curios items with modifiers.
It makes most sense with the max health increase modifier, but I could see it going well with others such as knockback resistance or movement speed.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I could see this working with curios however it would need some special balancing to make sure things are not over powered.

**Comment by Darkhax** [comment]
After reflecting on this further I don't think this will work with how the mod has been designed or balanced.
