### ISSUE TITLE
[Feature Suggestion] Is an attack range upgrade possible ?

### ISSUE THREAD

**Issue by Osl00** [Darkhax-Minecraft/Upgrade-Modifiers#4]
Some mod add mobs with more attack range and a knockback effect. So a little attack range inprovement would be welcome.
Thanks.

And keep the good job.

**Comment by Darkhax** [comment]
Hello, I agree that this would be a very cool idea to add. Unfortunately an attribute for this does not exist yet. Mobs use a different system for attacking that makes doing stuff like that easier. Ideally an attribute like this would be added by Forge as they already implement an attribute for the block breaking distance of an item.
