### ISSUE TITLE
[QUESTION] Update for 1.20.1? / Compat with Equipment Standard?

### ISSUE THREAD

**Issue by CanecaKun** [Darkhax-Minecraft/Upgrade-Modifiers#6]
### Question

Just wondering if you plan to update this mod for the popular versions as 1.20.1 for example, been looking for a mod to upgrade item attributes and yours was the only one i found

**Comment by Darkhax** [comment]
Hello, I would love to update this mod to 1.20.1 but there are too many other mods and versions that I need to update first. I may revisiit it in the future but it is not on my roadmap. I would recommend trying to find a different mod, or looking into what can be done with CraftTweaker scripts.
